### ISSUE TITLE
Confirm origins of Panopea-generosa-genes-annotations.tab

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Geoduck_Meth#16]
@sr320 can you confirm the origins of this file that is on OFS here https://osf.io/4etsu/ ?

related to https://github.com/RobertsLab/resources/issues/764 and https://github.com/hputnam/Geoduck_Meth/issues/13

**Comment by shellywanamaker** [comment]
I think this may be here somewhere https://github.com/sr320/nb-2020/tree/master/P_generosa

**Comment by shellywanamaker** [comment]
@kubu4 i think [Panopea-generosa-genes-annotations.tab](https://raw.githubusercontent.com/sr320/nb-2020/master/P_generosa/analyses/Panopea-generosa-genes-annotations.tab) came from [Panopea-generosa-v1.0.a4.gene.GOids.tab](https://raw.githubusercontent.com/sr320/nb-2020/master/P_generosa/data/Panopea-generosa-v1.0.a4.gene.GOids.tab) which I think came from you Nov 26 2019 GenSAS analysis?

**Comment by kubu4** [comment]
> Nov 26 2019 GenSAS analysis?

I don't have a notebook entry on this date for any GenSAS stuff. Can you elaborate on this when you have a sec?

**Comment by kubu4** [comment]
> Can you elaborate on this when you have a sec?

Never mind, I know what's going on here. That date is when that job in the GenSAS pipeline was created. I think the full GenSAS analysis completed in Dec. 2020.

**Comment by kubu4** [comment]
> i think Panopea-generosa-genes-annotations.tab came from Panopea-generosa-v1.0.a4.gene.GOids.tab which I think came from you Nov 26 2019 GenSAS analysis?

That file was not generated by GenSAS. The header indicates it is a GFF, but the file is not a GFF, and GenSAS never produced a file like that.

**Comment by shellywanamaker** [comment]
must be a file that resulting from a join of the GFF you made with GO annotations downloaded from Uniprot, like @sr320 did here [https://github.com/sr320/nb-2019/blob/master/P_generosa/32-Gene-GO-Annotations.ipynb](https://github.com/sr320/nb-2019/blob/master/P_generosa/32-Gene-GO-Annotations.ipynb)

**Comment by kubu4** [comment]
I'm fairly certain it was generated by @sr320.

**Comment by kubu4** [comment]
Explanation is the file was generated using GenSAS BLAST table results from intermediate gene models. Final gene annotations are magically determined by GenSAS evaluating BLAST results from multiple intermediate gene models.
